name: Run unit tests on main branch

on:
  push:
    branches:
      - main

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Set Node.js version to 16

      - name: Run unit tests
        run:  npx nightwatch -t test/amazon.test.js
